### PR TITLE
Added missing labels when creating first_hist and other_hist.

### PR DESCRIPTION
**Pull request by LucianU**
The plot shows the labels, but they are missing from the code.

### CODE REVIEW

**Comment by AllenDowney** [comment]
Thanks for this, but I left some of the labeling code out of the book on purpose just to simplify the code a little.  The code in the repo is complete.

**Comment by LucianU** [comment]
I see. It would be nice to specify this somewhere. If you already have, then I missed it.

**Comment by AllenDowney** [comment]
I haven't -- I just quietly dropped it, hoping no one would notice :)

**Comment by LucianU** [comment]
You know how beginners are, they get stuck on details :) There is another downside that occurred to me. People might doubt whether it's worth to point out other omissions, because they don't know if they're on purpose or not.

In any case, I want to say I'm grateful for this book and the fact that you made it available to everyone. Thank you!

**Comment by AllenDowney** [comment]
Understood.  Thanks again!

**Pull request closed without merging**
