### PR TITLE
#76 Knocking out low-hanging py2/py3 compatibility with futurize fix-ups

### PR DESCRIPTION
**Pull request by gbremer**
Fix-ups from futurize -- mainly print and division compatibility fixes. Tests run and pass with Py27 and Py36.

The notebooks have not been checked and ported yet.

### CODE REVIEW

**Comment by AllenDowney** [comment]
Thanks very much for this!  It looks like there are a couple of actual compatibility issues here that I would like to fix, but the majority of what futurize generates is not necessary, and makes the code less clean.

I will apply the changes that make a difference, though.

**Comment by gbremer** [comment]
I'm happy to clean those things up and send along a review -- just give me nudge to where you want things to go. I still need to go through the IPython noteooks as well so I expect to create at least one more pull request.

**Comment by AllenDowney** [comment]
Please take a look at   0571a26ed4b003c13adb08e9287785a0accdb17d

I tried to grab the changes from futurize that matter.

**Comment by gbremer** [comment]
Got it -- I'll follow your lead there going forward. I assumed you wanted compatibility between py27 and py3, yes? I don't sense the code is at a point where it would suffer by supporting both.

**Comment by AllenDowney** [comment]
Yes, supporting both is the goal.  Thanks!

**Pull request closed without merging**
